name: Build and Run CloudSim-AWS Simulation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Compile the simulation
      run: |
        mkdir -p out
        javac -cp "lib/*" -d out src/main/java/com/example/AWS_Lambda_Simulation.java

    - name: Run the simulation
      run: |
        java -cp "out:lib/*" com.example.AWS_Lambda_Simulation
